### ISSUE TITLE
On plugin load "Client sent workspace folders"

### ISSUE THREAD

**Issue by adamreid** [lapce-community/lapce-terraform-ls#2]
When loading the plugin or reloading it from the plugin manager this warning is shown in the UI of Lapce:

![image](https://github.com/panekj/lapce-terraform-ls/assets/1719988/b5a153bd-bc3d-42b7-b426-56ed7c0a0fc9)

So I'm reporting this bug.

**Comment by panekj** [comment]
This has been already fixed

**Comment by s3than** [comment]
This is occurring in nightly running a fresh install, with only this plugin installed.

Could you detail how to get the fix?
